"""tenant_initial_clean

Revision ID: 5d4c90634c12
Revises:
Create Date: 2026-01-22 14:49:00.813973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d4c90634c12"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_rates_to_credit",
        sa.Column("rate_id", sa.String(), nullable=False),
        sa.Column("from_asset_type", sa.Text(), nullable=True),
        sa.Column("rate_to_ets", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("rate_id"),
    )
    op.create_table(
        "comments",
        sa.Column("comment_id", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_table(
        "interest_canonical",
        sa.Column("canonical_id", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("canonical_id"),
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_table(
        "profile",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("gender", sa.Boolean(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_table(
        "comment_interactions",
        sa.Column("interaction_id", sa.String(), nullable=False),
        sa.Column("comment_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.comment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("interaction_id"),
    )
    op.create_table(
        "comment_post",
        sa.Column("comment_post_id", sa.String(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("comment_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.comment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.post_id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("comment_post_id"),
    )
    op.create_table(
        "education",
        sa.Column("education_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("education_level", sa.String(), nullable=True),
        sa.Column("institution_name", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("credential_type", sa.String(), nullable=True),
        sa.Column("credential_title", sa.Text(), nullable=True),
        sa.Column("issuing_organization", sa.Text(), nullable=True),
        sa.Column("credential_ref", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name="check_education_dates",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("education_id"),
    )
    op.create_table(
        "groups",
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("role", sa.Boolean(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("group_id"),
    )
    op.create_table(
        "identity_documents",
        sa.Column("identity_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("document_type", sa.Text(), nullable=True),
        sa.Column("document_number", sa.Text(), nullable=True),
        sa.Column("issued_date", sa.DateTime(), nullable=True),
        sa.Column("expiry_date", sa.DateTime(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("identity_id"),
    )
    op.create_table(
        "post_interactions",
        sa.Column("interaction_id", sa.String(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.post_id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("interaction_id"),
    )
    op.create_table(
        "user_actions",
        sa.Column("action_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("action_type", sa.Text(), nullable=True),
        sa.Column("object_type", sa.Text(), nullable=True),
        sa.Column("object_id", sa.String(), nullable=True),
        sa.Column("group_id", sa.String(), nullable=True),
        sa.Column("msg_scope", sa.SmallInteger(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("msg_scope IN (0, 1)", name="check_action_msg_scope"),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    op.create_table(
        "user_interests",
        sa.Column("interest_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("interest_text", sa.Text(), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("interest_id"),
    )
    op.create_table(
        "wallets",
        sa.Column("wallet_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("ets", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("wallet_id"),
    )
    op.create_table(
        "appointments",
        sa.Column("appointment_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("remind_enabled", sa.Boolean(), nullable=True),
        sa.Column("remind_before_minutes", sa.Integer(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.PrimaryKeyConstraint("appointment_id"),
    )
    op.create_table(
        "interest_mapping",
        sa.Column("interest_id", sa.String(), nullable=False),
        sa.Column("canonical_id", sa.String(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("mapped_by", sa.Text(), nullable=True),
        sa.Column("mapped_at", sa.DateTime(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_id"],
            ["interest_canonical.canonical_id"],
        ),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["user_interests.interest_id"],
        ),
        sa.PrimaryKeyConstraint("interest_id"),
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("msg_scope", sa.SmallInteger(), nullable=True),
        sa.Column("group_id", sa.String(), nullable=True),
        sa.Column("receiver_id", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("msg_scope IN (0, 1)", name="check_msg_scope"),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "polls",
        sa.Column("poll_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.profile_id"],
        ),
        sa.PrimaryKeyConstraint("poll_id"),
    )
    op.create_table(
        "wallet_assets",
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("wallet_id", sa.String(), nullable=False),
        sa.Column("asset_type", sa.Text(), nullable=True),
        sa.Column("asset_code", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.wallet_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("tx_id", sa.String(), nullable=False),
        sa.Column("wallet_id", sa.String(), nullable=False),
        sa.Column("asset_type", sa.Text(), nullable=True),
        sa.Column("direction", sa.SmallInteger(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("ref_type", sa.Text(), nullable=True),
        sa.Column("ref_id", sa.Text(), nullable=True),
        sa.Column("metadata_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("direction IN (1, -1)", name="check_wallet_tx_direction"),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.wallet_id"],
        ),
        sa.PrimaryKeyConstraint("tx_id"),
    )
    op.create_table(
        "poll_options",
        sa.Column("option_id", sa.String(), nullable=False),
        sa.Column("poll_id", sa.String(), nullable=False),
        sa.Column("option_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["polls.poll_id"],
        ),
        sa.PrimaryKeyConstraint("option_id"),
    )
    op.create_table(
        "poll_votes",
        sa.Column("poll_vote_id", sa.String(), nullable=False),
        sa.Column("option_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["poll_options.option_id"],
        ),
        sa.PrimaryKeyConstraint("poll_vote_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("poll_votes")
    op.drop_table("poll_options")
    op.drop_table("wallet_transactions")
    op.drop_table("wallet_assets")
    op.drop_table("polls")
    op.drop_table("messages")
    op.drop_table("interest_mapping")
    op.drop_table("appointments")
    op.drop_table("wallets")
    op.drop_table("user_interests")
    op.drop_table("user_actions")
    op.drop_table("post_interactions")
    op.drop_table("identity_documents")
    op.drop_table("groups")
    op.drop_table("education")
    op.drop_table("comment_post")
    op.drop_table("comment_interactions")
    op.drop_table("profile")
    op.drop_table("posts")
    op.drop_table("interest_canonical")
    op.drop_table("comments")
    op.drop_table("asset_rates_to_credit")
    # ### end Alembic commands ###
