"""add_user_id_to_profile

Revision ID: f248f041b3f4
Revises: 5d4c90634c12
Create Date: 2026-01-22 14:56:26.184654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f248f041b3f4"
down_revision: Union[str, None] = "5d4c90634c12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_profile_user_id"), "profile", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_user_id"), table_name="profile")
    op.drop_column("profile", "user_id")
    # ### end Alembic commands ###
